### ISSUE TITLE
Suggestions for Contributor Communications

### ISSUE THREAD

**Issue by erindcole** [erindcole/mentalhues#7]
As a contributor, how would you want to stay in the loop about the project? Do you like receiving emails in the form of newsletters? Do you want to be able to chat with other contributors? Is it important, as a contributor to Mental Hues, to remain anonymous to other contributors?

**Comment by andy5995** [comment]
I like using Slack workspaces (full-featured chat room). If you've never used one before, I'll invite you one that I host and you can check it out.

There's a "channel" option that sends a notification all users in that channel. The default settings for users means they'll got an email notification, or a notification to their mobile app if they have it installed. So i use that sparingly. :)

The other communication method I use is RSS. Each GitHub project actually has an RSS feed by default. Here's the one for your master branch:
https://github.com/erindcole/mentalhues/commits/master.atom

It's not ideal, but until a more user-friendly site feed is set up, it's one option that people can use if they wish.

**Comment by Islast** [comment]
I enjoy gitter, it's easy to access, has options for private conversations and supports markdown :sparkles: . On the other hand I believe you need to have a GitHub account to sign in which is not ideal for certain contributors.  

I've never warmed to slack, but it could be a good option for mentalhues. To access a slack chatroom you usually need to be invited (via the admin adding your email address), so it feels more private. 
Thinking about how a contributor would request access, it could work like joining a mailing list. In fact if you have a mailing list you could include a "I want to be added to the slack workspace" tickbox.

**Comment by andy5995** [comment]
@Islast 
A Slack workspace has an option to create a public invite link, which I post on the README of my projects. I don't have to manually invite anyone.

Though after reading your comments, I chatted with @julianguyen, the maintainer of the [If Me](https://github.com/julianguyen/ifme/) project. She was unaware of that feature, and apparently it's not enabled in her Slack workspace. Her guess was that the feature is in Beta and hasn't been rolled out to older clients yet; my guess was that when the feature was added, it didn't get migrated into older clients.

Either way, the feature is there now. :) I've created 3 workspaces in the last 2 months and they all had public invites enabled by default.

Gitter does have it's advantages, too, I agree. :) Looks like a Twitter account can also be used to sign into it.

Cheers!

**Comment by erindcole** [comment]
Thank you for the suggestions @Islast  and @andy5995 😃 I did make two gitter chats, one public and one private. The public chat is for anyone who would like to start contributing. The private chat is for the initial contributors that I'm bringing in specifically for the beginning stages of the project. A mailing list is a great idea too. I'm thinking about MailChimp. Do you have any other ideas? 

@andy5995 you are not the first to ask me to make a Slack workspace, and I am still considering it. I have heard about complaints with the amount of platforms out there for chat. Seems like you have to add a new app every time you meet a new person 😆

**Comment by andy5995** [comment]
>you are not the first to ask me to make a Slack workspace, and I am still considering it. I have heard about complaints with the amount of platforms out there for chat. Seems like you have to add a new app every time you meet a new person

Hehe.. yeah,I think I know what you mean. :) What matters most is use something you and your contributors are comfortable with.

I don't see a link anywhere to your public Gitter chat room. If you'd like to invite me sometime, I'd be interested in keeping an eye on the `mentalhues` progress and perhaps contributing from time-to-time.

>A mailing list is a great idea too. I'm thinking about MailChimp.

I've used it once as admin working for someone else's project. Seemed ok, and I haven't heard anything bad about MailChimp.

**Comment by erindcole** [comment]
@andy5995 check out the new commit to mentalhues/CONTRIBUTING.md for contact info
