### ISSUE TITLE
Finish Contributing Guidelines

### ISSUE THREAD

**Issue by erindcole** [erindcole/mentalhues#9]
This file is still unfinished. I need to continue the work.

**Comment by erindcole** [comment]
@Islat could you check out my contributing guidelines so far? I cited you too, so was hoping for you to check that out.

**Comment by Islast** [comment]
Hi @erindcole. I think you've done a great job. Reading this really reinforces my sense of what you're trying to create. I only have one comment, which is that @KirstieJane is the one you should be citing for these guidelines :sparkles:
